export const rssFeeds = [
  {
    name: "BBC News",
    url: "https://feeds.bbci.co.uk/news/rss.xml",
    category: "world",
    priority: 10,
  },
  {
    name: "Reuters Top News",
    url: "https://feeds.reuters.com/reuters/topNews",
    category: "world",
    priority: 10,
  },
  {
    name: "CNN Top Stories",
    url: "http://rss.cnn.com/rss/edition.rss",
    category: "world",
    priority: 9,
  },
  {
    name: "The Guardian World",
    url: "https://www.theguardian.com/world/rss",
    category: "world",
    priority: 9,
  },
  {
    name: "NYTimes Home",
    url: "https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml",
    category: "world",
    priority: 8,
  },
  {
    name: "Google News",
    url: "https://news.google.com/rss?hl=en-US&gl=US&ceid=US:en",
    category: "general",
    priority: 8,
  },
  {
    name: "Hacker News",
    url: "https://news.ycombinator.com/rss",
    category: "tech",
    priority: 10,
  },
  {
    name: "TechCrunch",
    url: "https://techcrunch.com/feed/",
    category: "tech",
    priority: 9,
  },
  {
    name: "The Verge",
    url: "https://www.theverge.com/rss/index.xml",
    category: "tech",
    priority: 9,
  },
  {
    name: "ArsTechnica",
    url: "https://arstechnica.com/feed/",
    category: "tech",
    priority: 8,
  },
  {
    name: "CNET",
    url: "https://www.cnet.com/rss/all/",
    category: "tech",
    priority: 8,
  },
  {
    name: "Wired",
    url: "https://www.wired.com/feed/rss",
    category: "tech",
    priority: 8,
  },
  {
    name: "Dev.to Latest",
    url: "https://dev.to/feed/tag/ai",
    category: "ai",
    priority: 7,
  },
  {
    name: "Medium Technology",
    url: "https://medium.com/feed/tag/technology",
    category: "tech",
    priority: 7,
  },
  {
    name: "Product Hunt",
    url: "https://www.producthunt.com/feed",
    category: "startup",
    priority: 7,
  },
  {
    name: "MIT Technology Review",
    url: "https://www.technologyreview.com/feed/",
    category: "ai",
    priority: 9,
  },
  {
    name: "NVIDIA Blog",
    url: "https://blogs.nvidia.com/feed/",
    category: "ai",
    priority: 8,
  },
  {
    name: "OpenAI Blog",
    url: "https://openai.com/blog/feed.xml",
    category: "ai",
    priority: 10,
  },
  {
    name: "Google AI Blog",
    url: "https://ai.googleblog.com/feeds/posts/default",
    category: "ai",
    priority: 10,
  },
  {
    name: "AWS Blog",
    url: "https://aws.amazon.com/blogs/aws/feed/",
    category: "cloud",
    priority: 8,
  },
  {
    name: "GitHub Blog",
    url: "https://github.blog/feed/",
    category: "dev",
    priority: 8,
  },
  {
    name: "CNBC Top News",
    url: "https://www.cnbc.com/id/100003114/device/rss/rss.html",
    category: "business",
    priority: 8,
  },
  {
    name: "Financial Times",
    url: "https://www.ft.com/?format=rss",
    category: "business",
    priority: 7,
  },
  {
    name: "ESPN Top News",
    url: "https://www.espn.com/espn/rss/news",
    category: "sports",
    priority: 7,
  },
  {
    name: "BBC Sport",
    url: "https://feeds.bbci.co.uk/sport/rss.xml",
    category: "sports",
    priority: 7,
  },
  {
    name: "Variety",
    url: "https://variety.com/feed/",
    category: "entertainment",
    priority: 7,
  },
  {
    name: "ScienceDaily Top",
    url: "https://www.sciencedaily.com/rss/top.xml",
    category: "science",
    priority: 7,
  },
  {
    name: "Medical News Today",
    url: "https://www.medicalnewstoday.com/rss",
    category: "health",
    priority: 6,
  },
  {
    name: "Politico Picks",
    url: "https://www.politico.com/rss/politicopicks.xml",
    category: "politics",
    priority: 6,
  },
];
